global using System.ComponentModel.DataAnnotations;
global using System.Text.RegularExpressions;
global using Microsoft.AspNetCore.Identity;
global using Chat.Domain.Enums;
global using Chat.Domain.Abstract;
global using Chat.Domain.DTOs;
global using Chat.Domain.Entities.Groups;
global using Chat.Domain.Web;
global using Chat.Domain.Entities.Connections;
